// <auto-generated />
using System;
using EyeTracking.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EyeTracking.Infrastructure.Db.Migrations
{
    [DbContext(typeof(EyeTrackingDb))]
    [Migration("20261003151546_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EyeTracking.Domain.AccessLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int?>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId", "CreatedAt")
                        .HasDatabaseName("ix_access_log_study");

                    b.ToTable("access_log", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.AiBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CostCapUnits")
                        .HasColumnType("float")
                        .HasColumnName("cost_cap_units");

                    b.Property<bool>("SendFreeText")
                        .HasColumnType("bit")
                        .HasColumnName("send_free_text");

                    b.Property<double>("SpentUnits")
                        .HasColumnType("float")
                        .HasColumnName("spent_units");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId")
                        .IsUnique();

                    b.ToTable("ai_budgets", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Correct")
                        .HasColumnType("bit")
                        .HasColumnName("correct");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("kind");

                    b.Property<string>("NextSegmentId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("next_segment_id");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("option");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("question_id");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("segment_id");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("int")
                        .HasColumnName("protocol_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("topic");

                    b.Property<string>("TopicFreeText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("topic_free_text");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProtocolId");

                    b.HasIndex("StudyId");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit")
                        .HasColumnName("accepted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params");

                    b.Property<string>("PerTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_target");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<double>("ResidualPxMedian")
                        .HasColumnType("float")
                        .HasColumnName("residual_px_median");

                    b.Property<double>("ResidualPxP90")
                        .HasColumnType("float")
                        .HasColumnName("residual_px_p90");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("calibrations", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Consent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AudioRecording")
                        .HasColumnType("bit")
                        .HasColumnName("audio_recording");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("given_at");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<bool>("Participate")
                        .HasColumnType("bit")
                        .HasColumnName("participate");

                    b.Property<int>("SheetVersion")
                        .HasColumnType("int")
                        .HasColumnName("sheet_version");

                    b.Property<bool>("VideoRecording")
                        .HasColumnType("bit")
                        .HasColumnName("video_recording");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("consents", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition");

                    b.Property<string>("FaceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("face_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<bool>("TextReviewed")
                        .HasColumnType("bit")
                        .HasColumnName("text_reviewed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("TopicTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("topic_tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("content_items", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.ContentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("key")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("path");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("ContentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_media_key");

                    b.ToTable("content_media", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.DebriefAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FormVersion")
                        .HasColumnType("int")
                        .HasColumnName("form_version");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<bool>("Skipped")
                        .HasColumnType("bit")
                        .HasColumnName("skipped");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("debrief_answers", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.DebriefForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("questions");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StudyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_debrief_forms_study_version");

                    b.ToTable("debrief_forms", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.DemographicsAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answers");

                    b.Property<int>("FormVersion")
                        .HasColumnType("int")
                        .HasColumnName("form_version");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("demographics_answers", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.DemographicsForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fields");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("published_at");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StudyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_form_version");

                    b.ToTable("demographics_forms", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.GazeSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Conf")
                        .HasColumnType("float")
                        .HasColumnName("conf");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int")
                        .HasColumnName("layout_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("region");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("segment");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit")
                        .HasColumnName("valid");

                    b.Property<double?>("X")
                        .HasColumnType("float")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("float")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.HasIndex("SessionId", "TMs")
                        .HasDatabaseName("ix_gaze_samples_session_t");

                    b.ToTable("gaze_samples", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.GenerationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<double>("CostActualUnits")
                        .HasColumnType("float")
                        .HasColumnName("cost_actual_units");

                    b.Property<double>("CostEstimateUnits")
                        .HasColumnType("float")
                        .HasColumnName("cost_estimate_units");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("kind");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result");

                    b.Property<string>("SegmentId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("segment_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("status");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("StudyId", "Status")
                        .HasDatabaseName("ix_generation_jobs_study_status");

                    b.ToTable("generation_jobs", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.InformationSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aims")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aims");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("benefits");

                    b.Property<string>("DataHandling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_handling");

                    b.Property<string>("DiscomfortSources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discomfort_sources");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("published_at");

                    b.Property<string>("StopRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stop_rules");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StudyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_sheet_version");

                    b.ToTable("information_sheets", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("InviteeEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("invitee_email");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("StudyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_invitation_code");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.LiveConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("avatar_provider");

                    b.Property<double>("CostUnits")
                        .HasColumnType("float")
                        .HasColumnName("cost_units");

                    b.Property<string>("EndReason")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("end_reason");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("ended_at");

                    b.Property<string>("InputMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("input_mode");

                    b.Property<int>("OffTopicStreak")
                        .HasColumnType("int")
                        .HasColumnName("off_topic_streak");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<string>("ReplyProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("reply_provider");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SttProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("stt_provider");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("topic");

                    b.Property<bool>("TranscriptAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("transcript_allowed");

                    b.Property<int>("TurnsUsed")
                        .HasColumnType("int")
                        .HasColumnName("turns_used");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("live_conversations", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.LiveTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Chars")
                        .HasColumnType("int")
                        .HasColumnName("chars");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<double>("CostUnits")
                        .HasColumnType("float")
                        .HasColumnName("cost_units");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("flags");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasColumnName("index");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("role");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int?>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("ConversationId", "Index")
                        .HasDatabaseName("ix_live_turns_conversation");

                    b.ToTable("live_turns", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.MeasurementSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowContinueWithoutValidation")
                        .HasColumnType("bit")
                        .HasColumnName("allow_continue_without_validation");

                    b.Property<int>("CalibrationPoints")
                        .HasColumnType("int")
                        .HasColumnName("calibration_points");

                    b.Property<double>("GazeConfThreshold")
                        .HasColumnType("float")
                        .HasColumnName("gaze_conf_threshold");

                    b.Property<double>("MinRegionToErrorRatio")
                        .HasColumnType("float")
                        .HasColumnName("min_region_to_error_ratio");

                    b.Property<double>("QualityMaxMissingShare")
                        .HasColumnType("float")
                        .HasColumnName("quality_max_missing_share");

                    b.Property<double>("QualityMaxUncertainShare")
                        .HasColumnType("float")
                        .HasColumnName("quality_max_uncertain_share");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<double>("ValidationMaxUncertain")
                        .HasColumnType("float")
                        .HasColumnName("validation_max_uncertain");

                    b.Property<double>("ValidationMinCorrect")
                        .HasColumnType("float")
                        .HasColumnName("validation_min_correct");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StudyId")
                        .IsUnique();

                    b.ToTable("measurement_settings", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("severity");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int?>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_observations_session");

                    b.HasIndex("StudyId");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("StudyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_participant_code");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessibilityNeeds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accessibility_needs");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FacePreference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("face_preference");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interests");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<string>("ResponseMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("response_mode");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("speed");

                    b.Property<string>("VoicePreference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("voice_preference");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("protocols", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.ReferenceRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int")
                        .HasColumnName("sample_count");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("settings");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("ValidCount")
                        .HasColumnType("int")
                        .HasColumnName("valid_count");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudyId");

                    b.ToTable("reference_recordings", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.ReferenceSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecordingId")
                        .HasColumnType("int")
                        .HasColumnName("recording_id");

                    b.Property<int>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit")
                        .HasColumnName("valid");

                    b.Property<double?>("X")
                        .HasColumnType("float")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("float")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId", "TMs")
                        .HasDatabaseName("ix_reference_samples_recording_t");

                    b.ToTable("reference_samples", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<bool>("CalibrationValid")
                        .HasColumnType("bit")
                        .HasColumnName("calibration_valid");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("camera");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device");

                    b.Property<string>("EndReason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("end_reason");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("ended_at");

                    b.Property<string>("GazeModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gaze_model");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<int?>("ProtocolId")
                        .HasColumnType("int")
                        .HasColumnName("protocol_id");

                    b.Property<string>("Screen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("screen");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<bool>("Synthetic")
                        .HasColumnType("bit")
                        .HasColumnName("synthetic");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("StudyId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.SessionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.SettingsVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rationale");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("values");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StudyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_settings_versions_study_version");

                    b.ToTable("settings_versions", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.StageResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComfortValue")
                        .HasColumnType("int")
                        .HasColumnName("comfort_value");

                    b.Property<double?>("CorrectRatio")
                        .HasColumnType("float")
                        .HasColumnName("correct_ratio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("decision");

                    b.Property<double>("InvalidShare")
                        .HasColumnType("float")
                        .HasColumnName("invalid_share");

                    b.Property<int>("LastTrialId")
                        .HasColumnType("int")
                        .HasColumnName("last_trial_id");

                    b.Property<int?>("NextStageIndex")
                        .HasColumnType("int")
                        .HasColumnName("next_stage_index");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("reason");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("StageIndex")
                        .HasColumnType("int")
                        .HasColumnName("stage_index");

                    b.Property<int>("Trials")
                        .HasColumnType("int")
                        .HasColumnName("trials");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("stage_results", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.StimulusLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("layout");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("segment");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int?>("StageIndex")
                        .HasColumnType("int")
                        .HasColumnName("stage_index");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("stimulus_layouts", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("RetentionPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("retention_policy");

                    b.HasKey("Id");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.StudyMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanLinkIdentity")
                        .HasColumnType("bit")
                        .HasColumnName("can_link_identity");

                    b.Property<int>("StudyId")
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    b.Property<string>("StudyRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("study_role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("StudyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_membership");

                    b.ToTable("study_memberships", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Trial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correct")
                        .HasColumnType("bit")
                        .HasColumnName("correct");

                    b.Property<int>("FaceLevel")
                        .HasColumnType("int")
                        .HasColumnName("face_level");

                    b.Property<string>("NumberShown")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("number_shown");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("position");

                    b.Property<string>("Response")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("response");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("int")
                        .HasColumnName("response_ms");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("StageIndex")
                        .HasColumnType("int")
                        .HasColumnName("stage_index");

                    b.Property<int>("TMs")
                        .HasColumnType("int")
                        .HasColumnName("t_ms");

                    b.Property<int>("TrialIndex")
                        .HasColumnType("int")
                        .HasColumnName("trial_index");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("trials", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.Validation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalibrationId")
                        .HasColumnType("int")
                        .HasColumnName("calibration_id");

                    b.Property<double>("CorrectRatio")
                        .HasColumnType("float")
                        .HasColumnName("correct_ratio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("layout");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit")
                        .HasColumnName("passed");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reasons");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int?>("SettingsVersion")
                        .HasColumnType("int")
                        .HasColumnName("settings_version");

                    b.Property<double>("SizeRatio")
                        .HasColumnType("float")
                        .HasColumnName("size_ratio");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("targets");

                    b.Property<double>("UncertainRatio")
                        .HasColumnType("float")
                        .HasColumnName("uncertain_ratio");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.HasIndex("SessionId");

                    b.ToTable("validations", (string)null);
                });

            modelBuilder.Entity("EyeTracking.Domain.AiBudget", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Answer", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Assignment", b =>
                {
                    b.HasOne("EyeTracking.Domain.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EyeTracking.Domain.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Protocol", null)
                        .WithMany()
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Calibration", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Consent", b =>
                {
                    b.HasOne("EyeTracking.Domain.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.ContentItem", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.ContentMedia", b =>
                {
                    b.HasOne("EyeTracking.Domain.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.DebriefAnswer", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.DebriefForm", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.DemographicsAnswer", b =>
                {
                    b.HasOne("EyeTracking.Domain.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.DemographicsForm", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.GazeSample", b =>
                {
                    b.HasOne("EyeTracking.Domain.StimulusLayout", null)
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.GenerationJob", b =>
                {
                    b.HasOne("EyeTracking.Domain.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.InformationSheet", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Invitation", b =>
                {
                    b.HasOne("EyeTracking.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.LiveConversation", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.LiveTurn", b =>
                {
                    b.HasOne("EyeTracking.Domain.LiveConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.MeasurementSettings", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Observation", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Participant", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Profile", b =>
                {
                    b.HasOne("EyeTracking.Domain.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Protocol", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.ReferenceRecording", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.ReferenceSample", b =>
                {
                    b.HasOne("EyeTracking.Domain.ReferenceRecording", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Session", b =>
                {
                    b.HasOne("EyeTracking.Domain.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.SessionEvent", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.SettingsVersion", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.StageResult", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.StimulusLayout", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.StudyMembership", b =>
                {
                    b.HasOne("EyeTracking.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Trial", b =>
                {
                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EyeTracking.Domain.Validation", b =>
                {
                    b.HasOne("EyeTracking.Domain.Calibration", null)
                        .WithMany()
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EyeTracking.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
