"""Ports the use cases depend on. Infrastructure implements them."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from eyetracking.domain.models import (
    Consent,
    DemographicsAnswer,
    DemographicsForm,
    InformationSheet,
    Invitation,
    Participant,
    Profile,
    Study,
    StudyMembership,
    User,
)


class UserRepo(Protocol):
    def add(self, user: User) -> User: ...
    def get(self, user_id: int) -> User | None: ...
    def by_email(self, email: str) -> User | None: ...
    def count(self) -> int: ...


class StudyRepo(Protocol):
    def add(self, study: Study) -> Study: ...
    def get(self, study_id: int) -> Study | None: ...
    def list_ids(self, ids: list[int]) -> list[Study]: ...
    def list_all(self) -> list[Study]: ...


class MembershipRepo(Protocol):
    def add(self, m: StudyMembership) -> StudyMembership: ...
    def for_user(self, user_id: int) -> list[StudyMembership]: ...
    def get(self, study_id: int, user_id: int) -> StudyMembership | None: ...


class ParticipantRepo(Protocol):
    def add(self, p: Participant) -> Participant: ...
    def by_user(self, user_id: int) -> Participant | None: ...
    def by_code(self, study_id: int, code: str) -> Participant | None: ...
    def list_for_study(self, study_id: int) -> list[Participant]: ...
    def count_for_study(self, study_id: int) -> int: ...


class InvitationRepo(Protocol):
    def add(self, inv: Invitation) -> Invitation: ...
    def by_token(self, token: str) -> Invitation | None: ...
    def count_for_study(self, study_id: int) -> int: ...


class SheetRepo(Protocol):
    def add(self, sheet: InformationSheet) -> InformationSheet: ...
    def current(self, study_id: int) -> InformationSheet | None: ...


class ConsentRepo(Protocol):
    def add(self, c: Consent) -> Consent: ...
    def latest(self, participant_id: int) -> Consent | None: ...
    def history(self, participant_id: int) -> list[Consent]: ...


class ProfileRepo(Protocol):
    def get(self, participant_id: int) -> Profile | None: ...
    def save(self, profile: Profile) -> Profile: ...


class DemographicsRepo(Protocol):
    def add_form(self, form: DemographicsForm) -> DemographicsForm: ...
    def current_form(self, study_id: int) -> DemographicsForm | None: ...
    def answers(self, participant_id: int) -> DemographicsAnswer | None: ...
    def save_answers(self, a: DemographicsAnswer) -> DemographicsAnswer: ...


class UnitOfWork(Protocol):
    users: UserRepo
    studies: StudyRepo
    memberships: MembershipRepo
    participants: ParticipantRepo
    invitations: InvitationRepo
    sheets: SheetRepo
    consents: ConsentRepo
    profiles: ProfileRepo
    demographics: DemographicsRepo

    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: int, role: str) -> str: ...
    def parse(self, token: str) -> int | None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


# ---------- step 2: sessions and measurement ----------

from eyetracking.domain.measurement import (  # noqa: E402
    Calibration,
    GazeSample,
    MeasurementSettings,
    Session,
    SessionEvent,
    StimulusLayout,
    Validation,
)


class SessionRepo(Protocol):
    def add(self, s: Session) -> Session: ...
    def get(self, session_id: int) -> Session | None: ...
    def list_for_participant(self, participant_id: int) -> list[Session]: ...
    def list_for_study(self, study_id: int) -> list[Session]: ...


class CalibrationRepo(Protocol):
    def add(self, c: Calibration) -> Calibration: ...
    def latest(self, session_id: int) -> Calibration | None: ...


class ValidationRepo(Protocol):
    def add(self, v: Validation) -> Validation: ...
    def latest(self, session_id: int) -> Validation | None: ...


class LayoutRepo(Protocol):
    def add(self, l: StimulusLayout) -> StimulusLayout: ...
    def latest(self, session_id: int) -> StimulusLayout | None: ...
    def session_all(self, session_id: int) -> list[StimulusLayout]: ...


class SampleRepo(Protocol):
    def add_many(self, samples: list[GazeSample]) -> int: ...
    def for_session(self, session_id: int) -> list[GazeSample]: ...
    def page(self, session_id: int, offset: int, limit: int) -> tuple[int, list[GazeSample]]: ...


class EventRepo(Protocol):
    def add(self, e: SessionEvent) -> SessionEvent: ...
    def for_session(self, session_id: int) -> list[SessionEvent]: ...


class MeasurementSettingsRepo(Protocol):
    def get(self, study_id: int) -> MeasurementSettings | None: ...
    def save(self, s: MeasurementSettings) -> MeasurementSettings: ...


class SettingsVersionRepo(Protocol):
    def add(self, v) -> object: ...
    def list_for_study(self, study_id: int) -> list: ...


class MeasurementUnitOfWork(UnitOfWork, Protocol):
    settings_versions: SettingsVersionRepo
    sessions: SessionRepo
    calibrations: CalibrationRepo
    validations: ValidationRepo
    layouts: LayoutRepo
    samples: SampleRepo
    events: EventRepo
    measurement_settings: MeasurementSettingsRepo


# ---------- step 3: protocols, content, assignments, practice ----------

from eyetracking.domain.practice import (  # noqa: E402
    Answer,
    Assignment,
    ContentItem,
    ContentMedia,
    Protocol,
    StageResult,
    Trial,
)


class ProtocolRepo(Protocol):
    def add(self, p: Protocol) -> Protocol: ...
    def get(self, protocol_id: int) -> Protocol | None: ...
    def list_for_study(self, study_id: int) -> list[Protocol]: ...
    def max_version(self, study_id: int) -> int: ...


class ContentRepo(Protocol):
    def add(self, c: ContentItem) -> ContentItem: ...
    def get(self, content_id: int) -> ContentItem | None: ...
    def list_for_study(self, study_id: int) -> list[ContentItem]: ...


class MediaRepo(Protocol):
    def add(self, m: ContentMedia) -> ContentMedia: ...
    def get(self, media_id: int) -> ContentMedia | None: ...
    def by_key(self, content_id: int, key: str) -> ContentMedia | None: ...
    def list_for_content(self, content_id: int) -> list[ContentMedia]: ...


class AssignmentRepo(Protocol):
    def add(self, a: Assignment) -> Assignment: ...
    def get(self, assignment_id: int) -> Assignment | None: ...
    def list_for_participant(self, participant_id: int) -> list[Assignment]: ...


class TrialRepo(Protocol):
    def add_many(self, trials: list[Trial]) -> int: ...
    def for_session(self, session_id: int) -> list[Trial]: ...


class StageResultRepo(Protocol):
    def add(self, r: StageResult) -> StageResult: ...
    def for_session(self, session_id: int) -> list[StageResult]: ...


class AnswerRepo(Protocol):
    def add(self, a: Answer) -> Answer: ...
    def for_session(self, session_id: int) -> list[Answer]: ...


class PracticeUnitOfWork(MeasurementUnitOfWork, Protocol):
    protocols: ProtocolRepo
    content: ContentRepo
    media: MediaRepo
    assignments: AssignmentRepo
    trials: TrialRepo
    stage_results: StageResultRepo
    answers: AnswerRepo


class MediaStore(Protocol):
    def save(self, relative_path: str, data: bytes) -> str: ...
    def absolute(self, relative_path: str) -> str: ...


class MediaSigner(Protocol):
    def sign(self, media_id: int) -> str: ...
    def verify(self, token: str) -> int | None: ...


# ---------- step 4: research and data ----------

from eyetracking.domain.research import AccessLogEntry  # noqa: E402


class AccessLogRepo(Protocol):
    def add(self, e: AccessLogEntry) -> AccessLogEntry: ...
    def list_for_study(self, study_id: int, limit: int) -> list[AccessLogEntry]: ...


class ResearchUnitOfWork(PracticeUnitOfWork, Protocol):
    access_log: AccessLogRepo

    def purge_participant_research_data(self, participant_id: int) -> dict: ...
    def delete_participant(self, participant_id: int) -> None: ...


# ---------- step 5: AI content generation ----------

from eyetracking.domain.ai import AiBudget, GenerationJob, TextRequest  # noqa: E402


class TextGenerator(Protocol):
    def info(self) -> dict: ...
    def estimate_cost(self, req: TextRequest) -> float: ...
    def generate(self, req: TextRequest) -> tuple[dict, dict]: ...


class VideoGenerator(Protocol):
    def info(self) -> dict: ...
    def estimate_cost(self, text: str, duration_s: float) -> float: ...
    def generate(self, text: str, face_id: str, voice_id: str) -> tuple[bytes, str, dict]: ...


class JobRepo(Protocol):
    def add(self, j: GenerationJob) -> GenerationJob: ...
    def get(self, job_id: int) -> GenerationJob | None: ...
    def list_for_study(self, study_id: int, status: str | None, content_id: int | None) -> list[GenerationJob]: ...
    def next_queued(self, now: datetime) -> GenerationJob | None: ...


class AiBudgetRepo(Protocol):
    def get(self, study_id: int) -> AiBudget | None: ...
    def save(self, b: AiBudget) -> AiBudget: ...


class AiUnitOfWork(ResearchUnitOfWork, Protocol):
    jobs: JobRepo
    ai_budgets: AiBudgetRepo


# ---------- step 6: supervised pilot ----------

from eyetracking.domain.pilot import DebriefAnswer, DebriefForm, Observation, ReferenceRecording  # noqa: E402


class ObservationRepo(Protocol):
    def add(self, o: Observation) -> Observation: ...
    def for_session(self, session_id: int) -> list[Observation]: ...
    def for_study(self, study_id: int) -> list[Observation]: ...


class DebriefFormRepo(Protocol):
    def add(self, f: DebriefForm) -> DebriefForm: ...
    def current(self, study_id: int) -> DebriefForm | None: ...
    def get_version(self, study_id: int, version: int) -> DebriefForm | None: ...


class DebriefAnswerRepo(Protocol):
    def add(self, a: DebriefAnswer) -> DebriefAnswer: ...
    def for_session(self, session_id: int) -> DebriefAnswer | None: ...
    def for_study(self, study_id: int) -> list[DebriefAnswer]: ...


class ReferenceRepo(Protocol):
    def add(self, r: ReferenceRecording, rows: list[tuple[int, float | None, float | None, bool]]) -> ReferenceRecording: ...
    def get(self, recording_id: int) -> ReferenceRecording | None: ...
    def for_session(self, session_id: int) -> list[ReferenceRecording]: ...
    def for_study(self, study_id: int) -> list[ReferenceRecording]: ...
    def samples(self, recording_id: int) -> list[tuple[int, float | None, float | None, bool]]: ...


class PilotUnitOfWork(AiUnitOfWork, Protocol):
    observations: ObservationRepo
    debrief_forms: DebriefFormRepo
    debrief_answers: DebriefAnswerRepo
    references: ReferenceRepo


# ---------- step 7: live avatar ----------

from eyetracking.domain.live import LiveConversation, LiveTurn  # noqa: E402


class LiveRepo(Protocol):
    def add_conversation(self, c: LiveConversation) -> LiveConversation: ...
    def conversation_for_session(self, session_id: int) -> LiveConversation | None: ...
    def add_turn(self, t: LiveTurn) -> LiveTurn: ...
    def turns(self, conversation_id: int) -> list[LiveTurn]: ...
    def open_for_study(self, study_id: int) -> list[LiveConversation]: ...


class ReplyGenerator(Protocol):
    """Writes the avatar's next reply as a dict matching domain.live.REPLY_SCHEMA."""

    def info(self) -> dict: ...
    def estimate_cost(self) -> float: ...
    def reply(self, system: str, conversation: str, topic: str) -> tuple[dict, dict]: ...


class SpeechToText(Protocol):
    """Turns one recorded utterance into text. Audio is processed in memory and never stored."""

    def info(self) -> dict: ...
    def transcribe(self, audio: bytes, content_type: str, language: str = "en") -> str: ...


class LiveAvatarProvider(Protocol):
    """The face and voice the participant sees and hears."""

    def info(self) -> dict: ...
    def client_config(self, avatar_id: str, voice_id: str) -> dict: ...
    def estimate_cost_per_minute(self) -> float: ...


class LiveUnitOfWork(PilotUnitOfWork, Protocol):
    live: LiveRepo
