"""Ports the use cases depend on. Infrastructure implements them."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from eyetracking.domain.models import (
    Consent,
    DemographicsAnswer,
    DemographicsForm,
    InformationSheet,
    Invitation,
    Participant,
    Profile,
    Study,
    StudyMembership,
    User,
)


class UserRepo(Protocol):
    def add(self, user: User) -> User: ...
    def get(self, user_id: int) -> User | None: ...
    def by_email(self, email: str) -> User | None: ...
    def count(self) -> int: ...


class StudyRepo(Protocol):
    def add(self, study: Study) -> Study: ...
    def get(self, study_id: int) -> Study | None: ...
    def list_ids(self, ids: list[int]) -> list[Study]: ...
    def list_all(self) -> list[Study]: ...


class MembershipRepo(Protocol):
    def add(self, m: StudyMembership) -> StudyMembership: ...
    def for_user(self, user_id: int) -> list[StudyMembership]: ...
    def get(self, study_id: int, user_id: int) -> StudyMembership | None: ...


class ParticipantRepo(Protocol):
    def add(self, p: Participant) -> Participant: ...
    def by_user(self, user_id: int) -> Participant | None: ...
    def by_code(self, study_id: int, code: str) -> Participant | None: ...
    def list_for_study(self, study_id: int) -> list[Participant]: ...
    def count_for_study(self, study_id: int) -> int: ...


class InvitationRepo(Protocol):
    def add(self, inv: Invitation) -> Invitation: ...
    def by_token(self, token: str) -> Invitation | None: ...
    def count_for_study(self, study_id: int) -> int: ...


class SheetRepo(Protocol):
    def add(self, sheet: InformationSheet) -> InformationSheet: ...
    def current(self, study_id: int) -> InformationSheet | None: ...


class ConsentRepo(Protocol):
    def add(self, c: Consent) -> Consent: ...
    def latest(self, participant_id: int) -> Consent | None: ...
    def history(self, participant_id: int) -> list[Consent]: ...


class ProfileRepo(Protocol):
    def get(self, participant_id: int) -> Profile | None: ...
    def save(self, profile: Profile) -> Profile: ...


class DemographicsRepo(Protocol):
    def add_form(self, form: DemographicsForm) -> DemographicsForm: ...
    def current_form(self, study_id: int) -> DemographicsForm | None: ...
    def answers(self, participant_id: int) -> DemographicsAnswer | None: ...
    def save_answers(self, a: DemographicsAnswer) -> DemographicsAnswer: ...


class UnitOfWork(Protocol):
    users: UserRepo
    studies: StudyRepo
    memberships: MembershipRepo
    participants: ParticipantRepo
    invitations: InvitationRepo
    sheets: SheetRepo
    consents: ConsentRepo
    profiles: ProfileRepo
    demographics: DemographicsRepo

    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: int, role: str) -> str: ...
    def parse(self, token: str) -> int | None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
