"""Ports the use cases depend on. Infrastructure implements them."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from eyetracking.domain.models import (
    Consent,
    DemographicsAnswer,
    DemographicsForm,
    InformationSheet,
    Invitation,
    Participant,
    Profile,
    Study,
    StudyMembership,
    User,
)


class UserRepo(Protocol):
    def add(self, user: User) -> User: ...
    def get(self, user_id: int) -> User | None: ...
    def by_email(self, email: str) -> User | None: ...
    def count(self) -> int: ...


class StudyRepo(Protocol):
    def add(self, study: Study) -> Study: ...
    def get(self, study_id: int) -> Study | None: ...
    def list_ids(self, ids: list[int]) -> list[Study]: ...
    def list_all(self) -> list[Study]: ...


class MembershipRepo(Protocol):
    def add(self, m: StudyMembership) -> StudyMembership: ...
    def for_user(self, user_id: int) -> list[StudyMembership]: ...
    def get(self, study_id: int, user_id: int) -> StudyMembership | None: ...


class ParticipantRepo(Protocol):
    def add(self, p: Participant) -> Participant: ...
    def by_user(self, user_id: int) -> Participant | None: ...
    def by_code(self, study_id: int, code: str) -> Participant | None: ...
    def list_for_study(self, study_id: int) -> list[Participant]: ...
    def count_for_study(self, study_id: int) -> int: ...


class InvitationRepo(Protocol):
    def add(self, inv: Invitation) -> Invitation: ...
    def by_token(self, token: str) -> Invitation | None: ...
    def count_for_study(self, study_id: int) -> int: ...


class SheetRepo(Protocol):
    def add(self, sheet: InformationSheet) -> InformationSheet: ...
    def current(self, study_id: int) -> InformationSheet | None: ...


class ConsentRepo(Protocol):
    def add(self, c: Consent) -> Consent: ...
    def latest(self, participant_id: int) -> Consent | None: ...
    def history(self, participant_id: int) -> list[Consent]: ...


class ProfileRepo(Protocol):
    def get(self, participant_id: int) -> Profile | None: ...
    def save(self, profile: Profile) -> Profile: ...


class DemographicsRepo(Protocol):
    def add_form(self, form: DemographicsForm) -> DemographicsForm: ...
    def current_form(self, study_id: int) -> DemographicsForm | None: ...
    def answers(self, participant_id: int) -> DemographicsAnswer | None: ...
    def save_answers(self, a: DemographicsAnswer) -> DemographicsAnswer: ...


class UnitOfWork(Protocol):
    users: UserRepo
    studies: StudyRepo
    memberships: MembershipRepo
    participants: ParticipantRepo
    invitations: InvitationRepo
    sheets: SheetRepo
    consents: ConsentRepo
    profiles: ProfileRepo
    demographics: DemographicsRepo

    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: int, role: str) -> str: ...
    def parse(self, token: str) -> int | None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


# ---------- step 2: sessions and measurement ----------

from eyetracking.domain.measurement import (  # noqa: E402
    Calibration,
    GazeSample,
    MeasurementSettings,
    Session,
    SessionEvent,
    StimulusLayout,
    Validation,
)


class SessionRepo(Protocol):
    def add(self, s: Session) -> Session: ...
    def get(self, session_id: int) -> Session | None: ...
    def list_for_participant(self, participant_id: int) -> list[Session]: ...
    def list_for_study(self, study_id: int) -> list[Session]: ...


class CalibrationRepo(Protocol):
    def add(self, c: Calibration) -> Calibration: ...
    def latest(self, session_id: int) -> Calibration | None: ...


class ValidationRepo(Protocol):
    def add(self, v: Validation) -> Validation: ...
    def latest(self, session_id: int) -> Validation | None: ...


class LayoutRepo(Protocol):
    def add(self, l: StimulusLayout) -> StimulusLayout: ...
    def latest(self, session_id: int) -> StimulusLayout | None: ...


class SampleRepo(Protocol):
    def add_many(self, samples: list[GazeSample]) -> int: ...
    def for_session(self, session_id: int) -> list[GazeSample]: ...
    def page(self, session_id: int, offset: int, limit: int) -> tuple[int, list[GazeSample]]: ...


class EventRepo(Protocol):
    def add(self, e: SessionEvent) -> SessionEvent: ...
    def for_session(self, session_id: int) -> list[SessionEvent]: ...


class MeasurementSettingsRepo(Protocol):
    def get(self, study_id: int) -> MeasurementSettings | None: ...
    def save(self, s: MeasurementSettings) -> MeasurementSettings: ...


class MeasurementUnitOfWork(UnitOfWork, Protocol):
    sessions: SessionRepo
    calibrations: CalibrationRepo
    validations: ValidationRepo
    layouts: LayoutRepo
    samples: SampleRepo
    events: EventRepo
    measurement_settings: MeasurementSettingsRepo


# ---------- step 3: protocols, content, assignments, practice ----------

from eyetracking.domain.practice import (  # noqa: E402
    Answer,
    Assignment,
    ContentItem,
    ContentMedia,
    Protocol,
    StageResult,
    Trial,
)


class ProtocolRepo(Protocol):
    def add(self, p: Protocol) -> Protocol: ...
    def get(self, protocol_id: int) -> Protocol | None: ...
    def list_for_study(self, study_id: int) -> list[Protocol]: ...
    def max_version(self, study_id: int) -> int: ...


class ContentRepo(Protocol):
    def add(self, c: ContentItem) -> ContentItem: ...
    def get(self, content_id: int) -> ContentItem | None: ...
    def list_for_study(self, study_id: int) -> list[ContentItem]: ...


class MediaRepo(Protocol):
    def add(self, m: ContentMedia) -> ContentMedia: ...
    def get(self, media_id: int) -> ContentMedia | None: ...
    def by_key(self, content_id: int, key: str) -> ContentMedia | None: ...
    def list_for_content(self, content_id: int) -> list[ContentMedia]: ...


class AssignmentRepo(Protocol):
    def add(self, a: Assignment) -> Assignment: ...
    def get(self, assignment_id: int) -> Assignment | None: ...
    def list_for_participant(self, participant_id: int) -> list[Assignment]: ...


class TrialRepo(Protocol):
    def add_many(self, trials: list[Trial]) -> int: ...
    def for_session(self, session_id: int) -> list[Trial]: ...


class StageResultRepo(Protocol):
    def add(self, r: StageResult) -> StageResult: ...
    def for_session(self, session_id: int) -> list[StageResult]: ...


class AnswerRepo(Protocol):
    def add(self, a: Answer) -> Answer: ...
    def for_session(self, session_id: int) -> list[Answer]: ...


class PracticeUnitOfWork(MeasurementUnitOfWork, Protocol):
    protocols: ProtocolRepo
    content: ContentRepo
    media: MediaRepo
    assignments: AssignmentRepo
    trials: TrialRepo
    stage_results: StageResultRepo
    answers: AnswerRepo


class MediaStore(Protocol):
    def save(self, relative_path: str, data: bytes) -> str: ...
    def absolute(self, relative_path: str) -> str: ...


class MediaSigner(Protocol):
    def sign(self, media_id: int) -> str: ...
    def verify(self, token: str) -> int | None: ...
